name: Continuous Integration

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin' # Use Temurin as the distribution

    - name: Build Spring Boot project
      run: |
        cd service # Adjust the path to where your backend code is located
        ./gradlew build -x test # Skip tests

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.9' # Match the Node.js version with your environment

    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Build Angular project
      run: |
        cd  client # Adjust the path to where your frontend code is located
        npm install
        npm run build

